# Pandas day 2

In [3]:
import pandas as pd

In [11]:
data = {
    "name": ["Ram", "Sita", "Hari", "Gita", "John", "asma", "bibek", "sabal"],
    "age": [22, 25, 28, 21, 30, 20, 31, 23],
    "salary": [30000, 45000, 50000, 28000, 60000, 45000, 40000, 50000],
    "city": ['kathmandu', 'pokhara', 'kathmandu', 'dhangadi', 'chitwan', 'dhading', 'pokhara', 'jhapa']
}

data_df = pd.DataFrame(data)

# top row
data_df.head()

   name  age  salary       city
0   Ram   22   30000  kathmandu
1  Sita   25   45000    pokhara
2  Hari   28   50000  kathmandu
3  Gita   21   28000   dhangadi
4  John   30   60000    chitwan

In [12]:
# bottom row
data_df.tail(2)

    name  age  salary     city
6  bibek   31   40000  pokhara
7  sabal   23   50000    jhapa

In [14]:
# shape of dataframe -> (row, col)
data_df.shape

(8, 4)

In [16]:
# cols name
print(data_df.columns)

Index(['name', 'age', 'salary', 'city'], dtype='str')

In [18]:
# data types
data_df.dtypes

name        str
age       int64
salary    int64
city        str
dtype: object

In [20]:
# general information
data_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    8 non-null      str
 1   age     8 non-null      int64
 2   salary  8 non-null      int64
 3   city    8 non-null      str
dtypes: int64(2), str(2)
memory usage: 388.0 bytes

In [29]:
# statistics analaysis
data_df.describe()

             age        salary
count   8.000000      8.000000
mean   25.000000  43500.000000
std     4.208834  10663.690061
min    20.000000  28000.000000
25%    21.750000  37500.000000
50%    24.000000  45000.000000
75%    28.500000  50000.000000
max    31.000000  60000.000000

In [30]:
print(data_df["age"].mean())
print(data_df["salary"].mean())

25.0
43500.0

## selecting cols

In [38]:
# selecting certain col
age_data = data_df["age"]
age_data

0    22
1    25
2    28
3    21
4    30
5    20
6    31
7    23
Name: age, dtype: int64

In [39]:
type(age_data)

pandas.Series

In [35]:
# selecting multiple cols
new_df = data_df[["name", "age", "salary"]]
new_df

    name  age  salary
0    Ram   22   30000
1   Sita   25   45000
2   Hari   28   50000
3   Gita   21   28000
4   John   30   60000
5   asma   20   45000
6  bibek   31   40000
7  sabal   23   50000

In [37]:
type(new_df)

pandas.DataFrame

## selecting rows - loc and iloc

In [44]:
# using iloc -> integer location
# first row
data_df.iloc[0]

name            Ram
age              22
salary        30000
city      kathmandu
Name: 0, dtype: object

In [45]:
# first 3 rows
data_df.iloc[0:3]

   name  age  salary       city
0   Ram   22   30000  kathmandu
1  Sita   25   45000    pokhara
2  Hari   28   50000  kathmandu

In [47]:
# specific row and col
data_df.iloc[0, 1]

np.int64(22)

In [50]:
# loc -> select using labels
data_df.loc[0]

name            Ram
age              22
salary        30000
city      kathmandu
Name: 0, dtype: object

In [52]:
data_df.loc[0, ['name', 'age']]

name    Ram
age      22
Name: 0, dtype: object

In [53]:
# multiple rows
data_df.loc[0:2, ['name', 'salary']]

   name  salary
0   Ram   30000
1  Sita   45000
2  Hari   50000

In [54]:
data_df.iloc[0:2]

   name  age  salary       city
0   Ram   22   30000  kathmandu
1  Sita   25   45000    pokhara

In [55]:
data_df.loc[0:2]

   name  age  salary       city
0   Ram   22   30000  kathmandu
1  Sita   25   45000    pokhara
2  Hari   28   50000  kathmandu

## filtering data

In [57]:
# age greater than 25
data_df[data_df["age"]>25]

    name  age  salary       city
2   Hari   28   50000  kathmandu
4   John   30   60000    chitwan
6  bibek   31   40000    pokhara

In [61]:
# Age greater than 22 AND salary greater than 40,000
data_df[
   ( data_df["age"] > 22) & (data_df["salary"] > 40000)
]

    name  age  salary       city
1   Sita   25   45000    pokhara
2   Hari   28   50000  kathmandu
4   John   30   60000    chitwan
7  sabal   23   50000      jhapa

and -> &, or -> |

# Reading CSV file

In [ ]:
# dataset url: https://www.kaggle.com/datasets/ihelon/coffee-sales

filepath = "./dataset/sale1.csv"
sales_df = pd.read_csv(filepath)

sales_df.head()

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte

In [65]:
sales_df.tail()

,date,datetime,cash_type,card,money,coffee_name
3631,2025-03-23,2025-03-23 10:34:54.894,card,ANON-0000-0000-1158,35.76,Cappuccino
3632,2025-03-23,2025-03-23 14:43:37.362,card,ANON-0000-0000-1315,35.76,Cocoa
3633,2025-03-23,2025-03-23 14:44:16.864,card,ANON-0000-0000-1315,35.76,Cocoa
3634,2025-03-23,2025-03-23 15:47:28.723,card,ANON-0000-0000-1316,25.96,Americano
3635,2025-03-23,2025-03-23 18:11:38.635,card,ANON-0000-0000-1275,35.76,Latte

In [67]:
row, col = sales_df.shape
print(f"rows: {row} cols: {col}")

rows: 3636 cols: 6

In [69]:
sales_df.dtypes

date               str
datetime           str
cash_type          str
card               str
money          float64
coffee_name        str
dtype: object

In [73]:
sales_df.describe()

             money
count  3636.000000
mean     31.746859
std       4.919926
min      18.120000
25%      27.920000
50%      32.820000
75%      35.760000
max      40.000000

In [74]:
sales_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3636 entries, 0 to 3635
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3636 non-null   str
 1   datetime     3636 non-null   str
 2   cash_type    3636 non-null   str
 3   card         3547 non-null   str
 4   money        3636 non-null   float64
 5   coffee_name  3636 non-null   str
dtypes: float64(1), str(5)
memory usage: 170.6 KB

### Data Analysis
Load -> Inspect -> Clean -> Analyze

### class work

In [ ]:
data = {
    "name": [
        "Ram", "Sita", "Hari",
        "Gita", "John", "Rita"
    ],
    "age": [20, 24, 22, 27, 30, 25],
    "city": [
        "Kathmandu", "Pokhara", "Kathmandu",
        "Chitwan", "Pokhara", "Kathmandu"
    ],
    "marks": [75, 88, 65, 92, 55, 81]
}

# df = pd.DataFrame(data)

- Display the complete DataFrame.
- Display the first 3 rows.
- Find the number of rows and columns.
- Display all column names.
- Select only the name column.
- Select name and marks.
- Find the average marks.
- Find the highest and lowest marks.
- Find students older than 23.
- Find students with marks greater than 80.
- Find students from Kathmandu.
- Find students from Kathmandu whose marks are greater than 75.
- Display the first student's data using iloc.
- Select rows 1–3 using iloc.
- Use describe() to inspect numerical columns.

## Data cleaning

In [16]:
import numpy as np
import pandas as pd

std_data = {
    "name": [
        "Ram", "Sita", "Hari", "Gita", "John", "Rita", "Gita"
    ],
    "age": [20, 24, 22, np.nan, 30, 25, np.nan],
    "city": [
        "Kathmandu", "Pokhara", "Kathmandu", "Chitwan", None, "Kathmandu", "Chitwan"
    ],
    "marks": ["75", "88", "65", "92", "55", "81", "92"]
}

std_df = pd.DataFrame(std_data)
std_df.head(10)

   name   age       city marks
0   Ram  20.0  Kathmandu    75
1  Sita  24.0    Pokhara    88
2  Hari  22.0  Kathmandu    65
3  Gita   NaN    Chitwan    92
4  John  30.0        NaN    55
5  Rita  25.0  Kathmandu    81
6  Gita   NaN    Chitwan    92

In [17]:
# check nan value
std_df.isnull()

    name    age   city  marks
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False   True  False  False
4  False  False   True  False
5  False  False  False  False
6  False   True  False  False

In [18]:
# count null values
std_df.isnull().sum()

name     0
age      2
city     1
marks    0
dtype: int64

In [27]:
std_df.isna().sum()

name     0
age      2
city     1
marks    0
dtype: int64

In [28]:
std_df.notna().sum()

name     7
age      5
city     6
marks    7
dtype: int64

In [19]:
std_df.isnull().sum().sort_values(ascending=False)

age      2
city     1
name     0
marks    0
dtype: int64

In [22]:
# drop missing value
new_df = std_df.dropna()
new_df.head(10)

   name   age       city marks
0   Ram  20.0  Kathmandu    75
1  Sita  24.0    Pokhara    88
2  Hari  22.0  Kathmandu    65
5  Rita  25.0  Kathmandu    81

In [26]:
new_df1 = std_df.dropna(subset=["age"])
new_df1

   name   age       city marks
0   Ram  20.0  Kathmandu    75
1  Sita  24.0    Pokhara    88
2  Hari  22.0  Kathmandu    65
4  John  30.0        NaN    55
5  Rita  25.0  Kathmandu    81

## ETL - Extract -> Transform -> Load