# Pandas Fundamentals
- used for data manipulation and analysis
- numpy is excellent for neumerical arrays, while pandas makes it easier to works with tabular data

In [2]:
import pandas as pd

## pandas series

In [10]:
ages = pd.Series([20, 25, 30, 35])

print(ages)

0    20
1    25
2    30
3    35
dtype: int64

In [12]:
# custom index
ages = pd.Series(
    [20, 25, 30, 35], 
    index=['A', 'B', 'C', 'D']
)
print(ages)

A    20
B    25
C    30
D    35
dtype: int64

In [14]:
print(ages["B"])

25

# Dataframe
- two dimensional table containing rows and cols

In [20]:
data = {
    "name": ["Ram", "Sita", "Hari", "Asma", "Bibek", "Sabal"],
    "age": [22, 25, 28, 22, 20, 19],
    "city": ["Kathmandu", "Pokhara", "Chitwan", "Butwal", "Nepalgunj", "Dhading"]
}


data_df = pd.DataFrame(data)
data_df

    name  age       city
0    Ram   22  Kathmandu
1   Sita   25    Pokhara
2   Hari   28    Chitwan
3   Asma   22     Butwal
4  Bibek   20  Nepalgunj
5  Sabal   19    Dhading

In [22]:
data_df.head()

    name  age       city
0    Ram   22  Kathmandu
1   Sita   25    Pokhara
2   Hari   28    Chitwan
3   Asma   22     Butwal
4  Bibek   20  Nepalgunj